apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-arena
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  ingresses:
    {{ #each ingresses as |ingress|}}
      - {{ingress}}
    {{/each}}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 512Mi
      cpu: "1"
    requests:
      memory: 256Mi
      cpu: 500m
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
  azure:
    application:
      enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
  envFrom:
